779 biorender demo
FredHutch/wiki pull request #1010
Opened 2024-06-05 22:24 UTC by matthewcchan

Corresponds to #779.
Added biorender info and how-to under dasl_demos

2024-06-13 04:35 UTC, tefirman requested changes
This is great, Matthew, thanks for contributing your BioRender knowledge! The content looks awesome, but I tried building the site locally and noticed that the images weren't quite compiling right with the relative path. I added some suggested changes to switch them to the absolute path (which compiles correctly) and put in one other small grammatical change. Thanks again for submitting this!

2024-06-13 04:35 UTC, tefirman commented on _dasldemos/biorender.md
> +![biorender_transport_example](./assets/biorender_example1.png)
```suggestion
![biorender_transport_example](/dasldemos/assets/biorender_example1.png)
```

2024-06-13 04:35 UTC, tefirman commented on _dasldemos/biorender.md
> +![](./assets/biorender_login.png)
```suggestion
![](/dasldemos/assets/biorender_login.png)
```

2024-06-13 04:35 UTC, tefirman commented on _dasldemos/biorender.md
> +![](./assets/biorender_apps.png)
```suggestion
![](/dasldemos/assets/biorender_apps.png)
```

2024-06-13 04:35 UTC, tefirman commented on _dasldemos/biorender.md
> +![](./assets/biorender_gallery.png)
```suggestion
![](/dasldemos/assets/biorender_gallery.png)
```

2024-06-13 04:35 UTC, tefirman commented on _dasldemos/biorender.md
> +![](./assets/biorender_artboard.png)
```suggestion
![](/dasldemos/assets/biorender_artboard.png)
```

2024-06-13 04:35 UTC, tefirman commented on _dasldemos/biorender.md
> +![](./assets/biorender_style.png)
```suggestion
![](/dasldemos/assets/biorender_style.png)
```

2024-06-13 04:35 UTC, tefirman commented on _dasldemos/biorender.md
> +![](./assets/biorender_export.png)
```suggestion
![](/dasldemos/assets/biorender_export.png)
```

2024-06-13 04:35 UTC, tefirman commented on _dasldemos/biorender.md
> +The Gallery the starting point for making and accessing files (illustrations, posters, graphs, etc). As an example, we will make a new illustration file by clicking on `+ Create new`,  then `Illustra
```suggestion
The Gallery is the starting point for making and accessing files (illustrations, posters, graphs, etc). As an example, we will make a new illustration file by clicking on `+ Create new`,  then `Illustration`.
```

2024-06-13 16:33 UTC, atombaby commented
The Biorender TOS includes a number of restrictions that would be good to note.  Of particular is 1.e.i.E:

> E) publish Completed Graphics that include BioRender Content in **any publication if you are not cited as the first or co-first author** of the publication due to copyright ownership of the publication being attributed to the first or co-first author. Any exceptions to this restriction must be approved in writing by BioRender.

(emphasis mine).

2024-07-03 21:38 UTC, matthewcchan commented
Thank you @tefirman and @atombaby for your comments. I have incorporated your edits in [7cfcdb8](https://github.com/FredHutch/wiki/pull/1010/commits/7cfcdb815790d8ded44688d0dd206edb3cc0751f).

2024-07-03 22:46 UTC, atombaby approved these changes

2024-07-12 06:18 UTC, merged